### ISSUE TITLE
Error downloading package

### ISSUE THREAD

**Issue by KMorozova** [NumbersInternational/flipMultivariates#19]
Hello, I am trying to download the package with RStudio, but get the following error:
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 46.18.27.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by jrwishart** [comment]
This is not an issue with `flipMultivariates` but an issue with too many requests to the github API which will block too many downloads (so you couldnt download `flipMultivariates` from github). There are two options
1. Wait until the download limit is increased and try again.
2. Get github Personal Access Token (PAT) to increase the limit. There is documentation that explains this on github as the error message stated. Some steps to create such a token from R are given here https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/
