### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by marnixkoops** [NumbersInternational/flipMultivariates#2]
Hi, thanks for the package. This is moreso a request than an issue.
Is it possible to submit it to CRAN so that it can be used on Kaggle within kernels?

Thanks!

Marnix

**Comment by mwmclean** [comment]
Hi, this is something we hope to do in the future.  Unfortunately, because we have so many dependencies on our other packages that are also not on CRAN, it's going to be a very large amount of work and not something we will be able to do in the short term.

**Comment by marnixkoops** [comment]
Ah, I understand. 
Thanks for your response, I will close this issue :).
