### ISSUE TITLE
issue installing flipMultivarite package specifically

### ISSUE THREAD

**Issue by katastrophy1025** [NumbersInternational/flipMultivariates#20]
Hi there

I'm trying to run an lda and would like to use the flipMultivarite package. 
when i use this method of installation:
library(devtools)
install_github("Displayr/flipMultivariates")
R installs a bunch of 'flip' packages (ie. flipData, flipStatistics...) EXCEPT flipMultivariate
therefore i cant load it using 'library' to run my lda function.

**Comment by mwmclean** [comment]
Please provide the exact error message you are getting from `install_github`.

**Comment by katastrophy1025** [comment]
> 

updating R and R studio ended up fixing the problem in the end but thank you!
