### ISSUE TITLE
Error in LDA function

### ISSUE THREAD

**Issue by katastrophy1025** [NumbersInternational/flipMultivariates#21]
i have a dataset where all my predictors are factors. When i try to run an lda i get the following error

> lda <- LDA(Group ~ ., data = test)
Error in if (!is.factor(required.data[, outcome.name]) & !IsCount(required.data[,  : 
  the condition has length > 1

**Comment by jrwishart** [comment]
Thanks for the bug report. I can reproduce. I'll look into fixing it.

**Comment by jrwishart** [comment]
Fixed in https://github.com/Displayr/flipMultivariates/pull/22
