### ISSUE TITLE
Prediction-Accuracy Table

### ISSUE THREAD

**Issue by katastrophy1025** [NumbersInternational/flipMultivariates#23]
i have created a prediction accuracy table using DIsplayR online platform, is there a way to pull out which participants are are being placed in each prediction?
For example, I'd like to be able to know which 21 indivuals are "observed AD" but "predicted MCI"

<img width="541" alt="Screen Shot 2022-08-09 at 11 07 52 AM" src="https://user-images.githubusercontent.com/108026188/183686949-7d88d734-8578-4d5e-9037-60ee2589b7a9.png">

**Comment by mwmclean** [comment]
In Displayr, if your LDA output is called `lda`, you can insert a Calculation and use `lda$model[[1]]` to view the original classes and `predict(lda)` to obtain the predicted classes. You haven't provided a reproducible example, but you should be able to answer your question with `which(lda$model[[1]] == "AD" & predict(lda) == "MCI")`.
